volumes:
  nextcloud:
  db:


services:

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /private/var/folders/docker-tp/nextcloud/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=batman
      - MYSQL_PASSWORD=batman
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - 81:80
    links:
      - db
    volumes:
      - /private/var/folders/docker-tp/nextcloud/data:/var/www/html/data
      - /private/var/folders/docker-tp/nextcloud/conf:/var/www/html/config
    environment:
      - MYSQL_PASSWORD=batman
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  symfony:
    container_name: symfony_container
    image: bitnami/symfony:latest
    ports:
      - "8000:8000"
    volumes:
      - "/private/var/folders/docker-tp/symfony/config:/app"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=symfonydb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=a75tat
      - SYMFONY_DATABASE_NAME=myapp
      - SYMFONY_DATABASE_PASSWORD=a6tf8s9t4a9s
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    depends_on:
      - symfonydb

  symfonydb:
    image: "bitnami/mariadb:11.2"

    volumes:
      - "/private/var/folders/docker-tp/symfony/data:/bitnami/mariadb"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=a75tat
      - MARIADB_PASSWORD=a6tf8s9t4a9s
      - MARIADB_DATABASE=myapp
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - "/private/var/folders/docker-tp/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - nextcloud
      - symfony
